spring:
    application:
        name: user-service
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        initialization-mode: always
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/user
        username: postgres
        password: admin

server:
    port: 10013
    
eureka:
  client:
    service-url: 
        defaultZone: http://localhost:10010/eureka